const courses=[
 {id:'mentoring',title:'Mentoring for Teachers',short:'Mentoring',img:'assets/mentoring.jpg',desc:'Methodology, structure, coaching tools and professional teaching development.',lessons:['Teaching framework','Class structure','Feedback & coaching','Professionalization']},
 {id:'fundamentals',title:'Fundamentals',short:'Fundamentals',img:'assets/fundamentals.jpg',desc:'Core technique, timing, connection, clean basics and the principles behind your movement.',lessons:['Posture & alignment','Timing & weight transfer','Connection principles','Quality of basics']},
 {id:'body1',title:'Body Movement I',short:'Body I',img:'assets/body1.jpg',desc:'Posture, isolations, waves and hip rolls with clean control and clear mechanics.',lessons:['Body posture','Rib cage isolations','Waves','Hip rolls']},
 {id:'body2',title:'Body Movement II',short:'Body II',img:'assets/body2.jpg',desc:'Cambrés, head rolls, chest rolls and advanced isolation pathways.',lessons:['Cambré mechanics','Head rolls','Chest rolls','Isolation combinations']},
 {id:'combined',title:'Body Movement Combined',short:'Combined',img:'assets/combined.jpg',desc:'Connect everything from Body Movement I & II into transitions and danceable sequences.',lessons:['Transition principles','Upper ↔ lower body','Dynamic pathways','Full combinations']}
];
const seedUsers=[
 {id:1,name:'Academy Admin',email:'admin@eyd-preview.local',role:'admin',access:['mentoring','fundamentals','body1','body2','combined']},
 {id:2,name:'Demo Student',email:'student@eyd-preview.local',role:'student',access:['fundamentals','body1']},
 {id:3,name:'New Student',email:'newstudent@example.com',role:'student',access:['fundamentals']}
];
let state={route:'home',session:null,users:JSON.parse(localStorage.getItem('eyd_preview_users')||'null')||seedUsers};
function save(){localStorage.setItem('eyd_preview_users',JSON.stringify(state.users))}
function iconLock(open){return open?'● ACCESS':'◆ LOCKED'}
function nav(){
 const s=state.session;
 return `<header class="nav"><div class="wrap navin"><div class="brand" onclick="go('home')"><img src="assets/eyd-logo.png"><span>ELENA & DENNIS<small>ACADEMY</small></span></div><div class="navlinks">
 <button class="desktop" onclick="go('home')">Modules</button>
 ${s?`<button onclick="go('${s.role==='admin'?'admin':'dashboard'}')">${s.role==='admin'?'Admin':'My Courses'}</button><button onclick="logout()">Logout</button>`:`<button onclick="go('login')">Login</button><button class="primary" onclick="go('register')">Register</button>`}
 </div></div></header>`
}
function footer(){return `<footer class="footer"><div class="wrap footerin"><div>© 2026 Elena & Dennis Academy · Preview build</div><div>Privacy · Imprint · elenadennisbachata@yahoo.com</div></div></footer>`}
function home(){return `${nav()}<main><div class="wrap hero"><div><div class="eyebrow">EYD Academy · Structured dance education</div><h1>Train deeper.<br>Access what you own.</h1><p>A private learning platform for dancers and teachers. Register once, access your purchased modules, and continue your training from anywhere.</p><div class="actions"><button class="primary" onclick="go('${state.session?state.session.role==='admin'?'admin':'dashboard':'login'}')">${state.session?'Open your academy':'Enter the academy'}</button><button class="secondary" onclick="document.getElementById('modules').scrollIntoView()">Explore modules</button></div></div><div class="heroVisual"><img class="bg" src="assets/hero-dark.jpg"><img class="people" src="assets/couple.jpg"><div class="heroBadge"><div class="eyebrow">Elena & Dennis</div><strong>Technique. Clarity. Growth.</strong><span>One account. Your purchased education.</span></div></div></div>
 <section id="modules" class="section"><div class="wrap"><div class="sectionTop"><div><div class="eyebrow">The academy</div><h2>Your modules</h2></div><p>Each course is linked to your account. Locked modules stay visible so students know what can be added later, while purchased courses open immediately.</p></div><div class="grid">${courses.map(c=>courseCard(c,false)).join('')}<div class="course"><div class="courseImg" style="display:grid;place-items:center;background:radial-gradient(circle at center,rgba(213,173,102,.18),#101017)"><span style="font-family:Georgia;font-size:30px;color:#d5ad66">Coming soon</span></div><div class="courseBody"><h3>New Intensive</h3><p>Future intensives can be added without rebuilding the member system.</p><div class="courseMeta"><span>Future module</span><span class="lock">◆ LOCKED</span></div></div></div></div></div></section>
 <section class="section"><div class="wrap"><div class="featureRow"><div class="feature"><b>🔐 Account-based access</b><p>Every student gets a personal dashboard. Courses appear based on their assigned purchases.</p></div><div class="feature"><b>🎬 Protected lessons</b><p>Production video delivery can use signed, expiring access rather than public MP4 URLs.</p></div><div class="feature"><b>⚙️ Simple administration</b><p>Search a student, toggle course access, and see their academy immediately.</p></div></div></div></section></main>${footer()}`}
function courseCard(c,dashboard){
 const u=state.session && state.users.find(x=>x.id===state.session.id); const open=!!u && (u.role==='admin'||u.access.includes(c.id));
 return `<article class="course"><div class="courseImg"><img src="${c.img}"><div class="tag">${open?'UNLOCKED':'MODULE'}</div></div><div class="courseBody"><h3>${c.title}</h3><p>${c.desc}</p><div class="courseMeta"><span>${open?`${c.lessons.length} core lessons`:'Access after confirmation'}</span><span class="${open?'open':'lock'}">${iconLock(open)}</span></div>${dashboard?`<div style="margin-top:15px"><button class="${open?'primary':'secondary'}" style="width:100%" ${open?`onclick="openCourse('${c.id}')"`:'disabled'}>${open?'Open course':'Locked'}</button></div>`:''}</div></article>`
}
function auth(type){const register=type==='register';return `${nav()}<div class="centerPage"><div class="authCard"><div class="eyebrow">EYD Academy</div><h1>${register?'Create account':'Welcome back'}</h1><p>${register?'Create your academy profile. In production, email verification would be required before activation.':'Sign in to access your purchased courses or administration.'}</p>${register?'<div class="field"><label>Full name</label><input id="name" placeholder="Your name"></div>':''}<div class="field"><label>Email</label><input id="email" autocomplete="email" placeholder="you@example.com"></div><div class="field"><label>Password</label><input id="password" type="password" autocomplete="current-password" placeholder="••••••••••"></div><button class="primary" style="width:100%" onclick="${register?'registerDemo()':'loginDemo()'}">${register?'Create demo account':'Sign in'}</button><div id="authError" class="error"></div>${!register?`<div class="demoBox"><b>Preview credentials — not production accounts</b><br>Admin: admin@eyd-preview.local / PreviewAdmin26!<br>Student: student@eyd-preview.local / PreviewStudent26!</div>`:''}</div></div>`}
function loginDemo(){const email=document.getElementById('email').value.trim().toLowerCase(), p=document.getElementById('password').value;let u;if(email==='admin@eyd-preview.local'&&p==='PreviewAdmin26!')u=state.users.find(x=>x.role==='admin');if(email==='student@eyd-preview.local'&&p==='PreviewStudent26!')u=state.users.find(x=>x.email==='student@eyd-preview.local');if(!u){document.getElementById('authError').textContent='Use one of the preview accounts shown below.';return}state.session={id:u.id,role:u.role};go(u.role==='admin'?'admin':'dashboard')}
function registerDemo(){const name=(document.getElementById('name').value||'New Student').trim(),email=document.getElementById('email').value.trim().toLowerCase();if(!email){document.getElementById('authError').textContent='Enter an email to create the preview account.';return}const id=Math.max(...state.users.map(u=>u.id))+1;state.users.push({id,name,email,role:'student',access:[]});save();state.session={id,role:'student'};go('dashboard')}
function dashboard(){if(!state.session||state.session.role==='admin')return admin();const u=state.users.find(x=>x.id===state.session.id);const unlocked=courses.filter(c=>u.access.includes(c.id)).length;return `${nav()}<main class="dash"><div class="wrap"><div class="dashHead"><div><div class="eyebrow">My Academy</div><h1>Welcome, ${escapeHtml(u.name)}</h1><div class="muted">Your personal course library and training progress.</div></div><button class="secondary" onclick="logout()">Sign out</button></div><div class="stats"><div class="stat"><span>Unlocked modules</span><strong>${unlocked}</strong></div><div class="stat"><span>Completed lessons</span><strong>3</strong></div><div class="stat"><span>Current progress</span><strong>38%</strong><div class="progressbar"><i></i></div></div></div><div class="sectionTop"><div><div class="eyebrow">Library</div><h2>My courses</h2></div><p>Only authorized modules can be opened. Locked modules remain visible and can be assigned by an administrator.</p></div><div class="grid">${courses.map(c=>courseCard(c,true)).join('')}</div></div></main>${footer()}`}
function admin(){if(!state.session||state.session.role!=='admin')return auth('login');const students=state.users.filter(u=>u.role==='student');return `${nav()}<main class="dash"><div class="wrap"><div class="dashHead"><div><div class="eyebrow">Administration</div><h1>EYD Academy Admin</h1><div class="muted">Manage student access and preview how the academy behaves.</div></div><button class="secondary" onclick="resetPreview()">Reset preview data</button></div><div class="adminLayout"><aside class="side"><button class="active">Overview</button><button>Students</button><button>Courses</button><button>Purchases</button><button>Settings</button></aside><section class="panel"><div class="notice">✓ This preview demonstrates the admin workflow. Production authentication, permissions and entitlements must be validated server-side.</div><div class="adminCards"><div class="mini"><span>Students</span><strong>${students.length}</strong></div><div class="mini"><span>Course modules</span><strong>${courses.length}</strong></div><div class="mini"><span>Access grants</span><strong>${students.reduce((a,u)=>a+u.access.length,0)}</strong></div></div><h2>Student access</h2><div class="muted">Click a module to grant or revoke access. Changes persist in this browser preview.</div><div class="toolbar"><input class="search" placeholder="Search students…" oninput="filterUsers(this.value)"><button class="primary" onclick="addDemoStudent()">+ Add student</button></div><div id="userList">${students.map(userRow).join('')}</div><div class="notice dangerNotice">Production plan: verified login → server-side entitlement check → signed video/file access. The preview itself intentionally does not pretend to be secure.</div></section></div></div></main>${footer()}`}
function userRow(u){return `<div class="userCard" data-search="${(u.name+' '+u.email).toLowerCase()}"><div class="userTop"><div class="identity"><div class="avatar">${u.name[0]||'U'}</div><div><strong>${escapeHtml(u.name)}</strong><small>${escapeHtml(u.email)}</small></div></div><span class="role">STUDENT</span></div><div class="entitlements">${courses.map(c=>`<button class="entitlement ${u.access.includes(c.id)?'yes':''}" onclick="toggleAccess(${u.id},'${c.id}')">${c.short}<span class="switch">${u.access.includes(c.id)?'✓':'＋'}</span></button>`).join('')}</div><div style="margin-top:11px;text-align:right"><button class="ghost" onclick="previewStudent(${u.id})">Preview as student →</button></div></div>`}
function coursePage(id){const c=courses.find(x=>x.id===id);const u=state.session&&state.users.find(x=>x.id===state.session.id);const open=u&&(u.role==='admin'||u.access.includes(id));if(!open)return dashboard();return `${nav()}<main class="coursePage"><div class="wrap"><button class="ghost" onclick="go('${u.role==='admin'?'admin':'dashboard'}')">← Back</button><div class="courseHero"><img src="${c.img}"><div><div class="eyebrow">Unlocked module</div><h1>${c.title}</h1><p class="muted" style="font-size:16px;line-height:1.65">${c.desc}</p><div class="notice">Your access is active. In production, every lesson and media request will be checked against your account entitlement.</div></div></div><div class="videoMock"><div class="play">▶</div></div><div class="lessons"><div class="sectionTop"><div><div class="eyebrow">Course curriculum</div><h2>Lessons</h2></div></div>${c.lessons.map((l,i)=>`<div class="lesson"><div><strong>${String(i+1).padStart(2,'0')} · ${l}</strong><small>${i===0?'Available now':'Continue your course'}</small></div><span class="open">OPEN →</span></div>`).join('')}</div></div></main>${footer()}`}
function toggleAccess(uid,cid){const u=state.users.find(x=>x.id===uid);u.access=u.access.includes(cid)?u.access.filter(x=>x!==cid):[...u.access,cid];save();render()}
function previewStudent(uid){const u=state.users.find(x=>x.id===uid);state.session={id:u.id,role:'student'};go('dashboard')}
function addDemoStudent(){const n=state.users.filter(x=>x.role==='student').length+1;state.users.push({id:Math.max(...state.users.map(x=>x.id))+1,name:`Demo Student ${n}`,email:`student${n}@example.com`,role:'student',access:[]});save();render()}
function filterUsers(q){document.querySelectorAll('.userCard').forEach(el=>el.style.display=el.dataset.search.includes(q.toLowerCase())?'':'none')}
function resetPreview(){localStorage.removeItem('eyd_preview_users');state.users=JSON.parse(JSON.stringify(seedUsers));render()}
function logout(){state.session=null;go('home')}
function openCourse(id){state.route='course:'+id;render();window.scrollTo(0,0)}
function go(route){state.route=route;render();window.scrollTo(0,0)}
function escapeHtml(s){return String(s).replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function render(){let html;if(state.route==='home')html=home();else if(state.route==='login')html=auth('login');else if(state.route==='register')html=auth('register');else if(state.route==='dashboard')html=dashboard();else if(state.route==='admin')html=admin();else if(state.route.startsWith('course:'))html=coursePage(state.route.split(':')[1]);else html=home();document.getElementById('app').innerHTML=html}
const qp=new URLSearchParams(location.search);if(qp.get('view')==='admin'){const a=state.users.find(x=>x.role==='admin');state.session={id:a.id,role:'admin'};state.route='admin'}else if(qp.get('view')==='student'){const u=state.users.find(x=>x.email==='student@eyd-preview.local');state.session={id:u.id,role:'student'};state.route='dashboard'}
render();
